<a href="https://colab.research.google.com/github/gaetanosaurio/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# **TENSORS**

*   A torch.tensor is a multidimensional vector containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPUs (vs. regular CPUs).
* Default data type pf float32
* More suitable for Deep LEarning than a numpy array.



# **LISTS**

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

# **NUMPY ARRAYS**

In [ ]:
np1 = np.random.rand(3, 4)
np1

array([[0.02218916, 0.46938052, 0.0709323 , 0.8413465 ],
       [0.18468173, 0.31422439, 0.97648347, 0.16117429],
       [0.78696059, 0.64304666, 0.19351279, 0.99861024]])

In [ ]:
np1.dtype

dtype('float64')

# **TENSORS**

In [ ]:
tensor_2d = torch.rand(3, 4)
tensor_2d, tensor_2d.dtype

(tensor([[0.2176, 0.0928, 0.5873, 0.7872],
         [0.6579, 0.2370, 0.9185, 0.9169],
         [0.8835, 0.1778, 0.8417, 0.2856]]),
 torch.float32)

In [ ]:
tensor_3d = torch.rand(2,3,4)
tensor_3d

tensor([[[0.9714, 0.5285, 0.6625, 0.8429],
         [0.9032, 0.7504, 0.0255, 0.2738],
         [0.2743, 0.1958, 0.9490, 0.4917]],

        [[0.3085, 0.4116, 0.7336, 0.8823],
         [0.5894, 0.9935, 0.8474, 0.0313],
         [0.2274, 0.8538, 0.4295, 0.7866]]])

In [ ]:
# Create tensor out of numpy array - - it will have a float64 data type, as in numpy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0222, 0.4694, 0.0709, 0.8413],
        [0.1847, 0.3142, 0.9765, 0.1612],
        [0.7870, 0.6430, 0.1935, 0.9986]], dtype=torch.float64)